### PR TITLE
Task84 down telemetry program 370 376

### PR DESCRIPTION
**Pull request by 7ofNine**
Please assign new task

### CODE REVIEW

**Comment by thewonderidiot** [comment]
Thanks! I'll give it a once-over and merge it in tonight. Any requests on size the new task or anything?

**Comment by 7ofNine** [comment]
No special requirements. I was involved in some of the previous transcriptions and have an idea of what to expect.

**Comment by thewonderidiot** [comment]
Throwing a random dart... [IMU COMPENSATION PACKAGE](https://github.com/rburkey2005/virtualagc/issues/75)?

**Comment by thewonderidiot** [comment]
Merged, which finishes transcription of #84. Thanks!

**Comment by 7ofNine** [comment]
Bullseye. Go for it.

**Pull request merged**
