### PR TITLE
Use common Makefile

### PR DESCRIPTION
**Pull request by jimlawton**
Change the flight builds to use a common make include file (`Makefile.inc` at top-level). 

 - This means we can modify build rules in one place. 
 - Differences in YUL options per-flight are specified using the `EXTRA_YUL_ARGS` variable, see `Solarium055` for an example.
 - Added a `format` target. This reformats all the sources in a flight directory with `yaYUL --format`.

### CODE REVIEW

**Comment by rburkey2005** [comment]
Seems reasonable.  I often do this kind of thing, and after a while nobody understands how it works any longer (including me), but this doesn't seem to be likely to happen in this case.  I do notice that the new Makefile.inc still lists its name (in the file's header comments) as just "Makefile".

**Comment by jimlawton** [comment]
Argh, didn't read your comment properly before I merged.

**Comment by jimlawton** [comment]
I'll fix it.

**Comment by jimlawton** [comment]
https://github.com/rburkey2005/virtualagc/pull/158

**Pull request merged**
